# The default values for the environment variables used here
# are defined in the .env file

services:
  vbox:
    image: $IMAGE_NAME
    build:
      context: arch
      args:
        - VMDIR
        - VBUSR
        - VBUID
        - TZONE
    container_name: vbox-$VBGUEST
    healthcheck:
      disable: true
    restart: "no"
    #restart: unless-stopped
    stop_grace_period: $GRACE_PERIOD
    #stop_signal: SIGINT
    ports:
      - $VRDPIP:$VRDP:$VRDP
    networks:
      - f-net
    volumes:
      - $VMSRC:$VMDIR
      - vbusr:/home/$VBUSR
    working_dir: /home/$VBUSR
    user: $VBUSR
    devices:
      - "/dev/vboxdrv:/dev/vboxdrv"
      - "/dev/vboxdrvu:/dev/vboxdrvu"

volumes:
  vbusr:

networks:
  f-net:
  # The following lines are optional
  # Note, the explicit CIDR/IP must be unique for every container
    #ipam:
      #config:
        #- subnet: 172.30.30.0/30
          #gateway: 172.30.30.1
