#!/usr/bin/env bash
# set-perm-vmsrc

# Use .env to get VBGUEST, VMSRC, and VBUID values
# VBGUEST is required to calculate the default VMSRC value
# Set rwXrX permissions on $VMSRC for $VBUID


while read -r pair
do eval "$pair"
# inline comments in .env are not supported
done < <( grep -sP '^\s*VBGUEST=|^\s*VMSRC=|^\s*VBUID=' "${0%/*}/.env" )
unset pair

# test -n "$VMSRC" && test -n "$VBUID"

if test -d "$VMSRC"
then
    chown -cR "$VBUID":"$VBUID" "$VMSRC"
    chmod -cR u=rwX,g=rX,o= "$VMSRC"
    echo
    find "$VMSRC" -print0 | sort -hz | xargs -r0 ls -lhad --color=auto
else
    echo "Error: '$VMSRC' is not a directory."
fi
